--- #YAML:1.0
name:               Crypt-Rijndael_PP
version:            0.05
abstract:           Pure Perl implementation of Rijndael (AES)
author:
    - Christian Lackas, <delta@lackas.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
